export const TEXTES = {
  fr: {
    dir: "ltr",
    nav: {
      accueil: "Accueil",
      assurances: "Nos assurances",
      apropos: "À propos",
      publications: "Publications",
      paiement: "Paiement",
      espace: "Administration",
      pourquoi: "Pourquoi nous ?",
      faq: "FAQ",
      contact: "Contact",
      devis: "Demander un devis",
      menu: "Ouvrir le menu",
      fermer: "Fermer le menu",
    },
    hero: {
      badge: "Agent Wafa Assurance",
      lieu: "Massira 2 – Addoha, Marrakech",
      titre1: "Votre assurance,",
      titre2: "notre engagement.",
      sous: "Assurances Ahl Al Khair vous accompagne à Massira 2, en face Carrefour Abwab Addoha à Marrakech, avec des solutions d'assurance adaptées à vos besoins.",
      devis: "Demander un devis",
      contact: "Nous contacter",
      couverture: "Ce que nous couvrons",
    },
    services: {
      titre: "Nos solutions d'assurance",
      sous: "Des solutions adaptées aux particuliers et aux professionnels.",
      plus: "En savoir plus",
      liste: [
        ["Assurance Automobile", "Protégez votre véhicule et conduisez en toute sérénité."],
        ["Assurance Habitation", "Votre logement et vos biens couverts au quotidien."],
        ["Assurance Santé", "Une couverture des soins pour vous et votre famille."],
        ["Assurance Accident", "Une protection en cas d'accident de la vie courante."],
        ["Assurance Professionnelle", "Des garanties adaptées à votre activité et à vos locaux."],
        ["Assurance Voyage", "Partez couvert, au Maroc comme à l'étranger."],
      ],
    },
    agence: {
      titre: "Une agence proche de vous à Massira 2",
      texte: "Située Massira 2 B n°823, en face Carrefour Abwab Addoha à Marrakech, Assurances Ahl Al Khair vous accompagne dans vos démarches d'assurance avec un service de proximité et un accompagnement personnalisé.",
      bouton: "Voir notre localisation",
      points: [["Massira 2 B n°823 — Addoha, Marrakech", "En face Carrefour Abwab Addoha"], ["Agent Wafa Assurance", "Notre partenaire"], ["06 08 52 40 44", "Nous joindre directement"]],
    },
    pourquoi: {
      titre: "Pourquoi choisir Assurances Ahl Al Khair ?",
      sous: "Quatre engagements qui guident notre travail au quotidien.",
      liste: [
        ["Proximité", "Une agence locale à Massira 2, Marrakech."],
        ["Accompagnement", "Un accompagnement personnalisé selon vos besoins."],
        ["Conseil", "Des conseils adaptés à votre situation."],
        ["Réactivité", "Une équipe disponible pour répondre à vos demandes."],
      ],
    },
    devis: {
      titre: "Demandez votre devis",
      sous: "Décrivez votre besoin, nous revenons vers vous rapidement.",
      nom: "Nom complet",
      tel: "Téléphone",
      email: "Email",
      type: "Type d'assurance",
      typeVide: "Choisissez une assurance",
      message: "Message",
      messagePlaceholder: "Précisez votre besoin en quelques lignes",
      envoyer: "Envoyer ma demande",
      envoi: "Envoi en cours…",
      succesTitre: "Demande envoyée",
      succesTexte: "Merci, votre demande a bien été transmise. Nous vous recontactons au numéro indiqué.",
      autre: "Envoyer une autre demande",
      types: ["Automobile", "Habitation", "Santé", "Accident", "Professionnelle", "Voyage"],
      erreurs: {
        nom: "Indiquez votre nom complet.",
        tel: "Indiquez un numéro de téléphone valide.",
        email: "Indiquez une adresse email valide.",
        type: "Choisissez un type d'assurance.",
        message: "Votre message est trop court.",
      },
      note: "Vos informations servent uniquement à traiter votre demande.",
    },
    localisation: {
      titre: "Retrouvez-nous à Massira 2",
      sous: "Massira 2 B n°823, en face Carrefour Abwab Addoha — Marrakech",
      maps: "Voir sur Google Maps",
      itineraire: "Itinéraire",
      carte: "Carte du quartier Massira 2, en face Carrefour Abwab Addoha à Marrakech",
    },
    apropos: {
      titre: "À propos d'Assurances Ahl Al Khair",
      p1: "Assurances Ahl Al Khair est une agence d'assurance située Massira 2 B n°823, en face Carrefour Abwab Addoha à Marrakech, agissant en tant qu'agent Wafa Assurance.",
      p2: "Notre objectif est d'accompagner nos clients avec proximité, conseil et professionnalisme dans leurs besoins en assurance.",
    },
    faq: {
      titre: "Questions fréquentes",
      sous: "Les réponses aux demandes que nous recevons le plus souvent.",
      liste: [
        ["Comment demander un devis ?", "Remplissez le formulaire de devis sur cette page, ou appelez-nous directement au 06 08 52 40 44. Nous revenons vers vous avec une proposition adaptée."],
        ["Quels documents sont nécessaires pour une assurance automobile ?", "La carte grise du véhicule, votre carte d'identité nationale et votre permis de conduire. Si le véhicule était déjà assuré, apportez également le relevé d'information de votre assureur précédent."],
        ["Quels types d'assurances proposez-vous ?", "Nous proposons l'assurance automobile, habitation, santé, accident, professionnelle et voyage."],
        ["Comment contacter l'agence ?", "Par téléphone ou par WhatsApp au 06 08 52 40 44, ou en passant directement à l'agence."],
        ["Où se trouve Assurances Ahl Al Khair ?", "Notre agence se situe à Massira 2 B n°823, en face du Carrefour Abwab Addoha, à Marrakech."],
      ],
    },
    flyers: {
      titre: "Nos publications",
      sous: "Les campagnes et offres en cours de l'agence.",
      agrandir: "Agrandir",
      telecharger: "Télécharger",
      fermer: "Fermer",
      precedent: "Publication précédente",
      suivant: "Publication suivante",
    },
    conventions: {
      titre: "Nos conventions",
      sous: "Des accords signés avec des institutions de référence, au bénéfice de leurs affiliés.",
    },
    contact: {
      titre: "Contactez-nous",
      sous: "Nous répondons à vos questions et vous orientons vers la bonne couverture.",
      appeler: "Appeler",
      whatsapp: "WhatsApp",
      maps: "Google Maps",
    },
    appel: {
      secours: "L'appel n'a pas démarré ? Composez ce numéro :",
      copier: "Copier", copie: "Copié", fermer: "Fermer",
    },
    captcha: {
      label: "Je ne suis pas un robot",
      chargement: "Chargement de la vérification…",
      erreur: "Confirmez que vous n'êtes pas un robot.",
    },
    paiement: {
      titre: "Modalités de paiement",
      sous: "Réglez votre prime en espèces à l'agence, en une fois ou de façon fractionnée.",
      note: "Aucun paiement n'est encaissé en ligne. Tous les règlements se font directement à l'agence, contre remise d'un reçu.",
      champ: "Mode de paiement souhaité",
      champVide: "Choisissez un mode de paiement",
    },
    assistant: {
      ouvrir: "Assistant en ligne",
      titre: "Assistant Ahl Al Khair",
      sous: "Réponses immédiates aux questions courantes",
      placeholder: "Posez votre question…",
      envoyer: "Envoyer",
      fermer: "Fermer l'assistant",
      accueil: "Bonjour. Je réponds aux questions courantes sur nos assurances, l'adresse de l'agence, les documents à fournir et les moyens de paiement. Pour un devis ou un dossier personnel, un conseiller vous répondra directement.",
      inconnu: "Je n'ai pas la réponse à cette question. Un conseiller de l'agence vous répondra mieux que moi.",
      suggestions: ["Où êtes-vous situés ?", "Documents pour assurer une voiture", "Comment payer ma prime ?", "Déclarer un sinistre"],
      appeler: "Appeler l'agence",
      avertissement: "Assistant automatique. Les réponses sont indicatives et ne remplacent pas votre conseiller.",
    },
    connexion: {
      retour: "Retour au site",
      reserve: "Accès réservé",
      titre: "Administration",
      sous: "Cet espace est réservé à l'équipe de l'agence. Les clients consultent librement le site et nous joignent par téléphone ou WhatsApp.",
      pasDeCompte: "Vous êtes client ?",
      retourSite: "Revenir au site",
      email: "Adresse email",
      motDePasse: "Mot de passe",
      afficher: "Afficher le mot de passe",
      masquer: "Masquer le mot de passe",
      seConnecter: "Se connecter",
      envoi: "Connexion…",
      demoTitre: "Accès de démonstration",
      erreurEmail: "Renseignez votre adresse email.",
      erreurMdp: "Renseignez votre mot de passe.",
      erreurIdentifiants: "Email ou mot de passe incorrect.",
    },
    espace: {
      deconnexion: "Déconnexion",
      administration: "Administration",
      demandes: "Demandes de devis", sinistres: "Sinistres", tableauBord: "Tableau de bord",
      clientsOnglet: "Clients", publications: "Publications",
      fiches: "fiches clients", telephone: "Téléphone", contrats: "Contrats",
      primeAnnuelle: "Prime annuelle", appeler: "Appeler", telecharger: "Télécharger",
      enAttente: "en attente de traitement", dossiersOuverts: "dossiers ouverts", auTotal: "au total",
      prendreEnCharge: "Prendre en charge", accepter: "Accepter", refuser: "Refuser",
      mandater: "Mandater un expert", cloturer: "Clôturer",
      vueEnsemble: "Vue d'ensemble de l'activité de l'agence.",
      primesSignees: "Primes signées", clients: "Clients", parProduit: "Demandes par produit",
      nom: "Nom", statut: "Statut", action: "Action",
      enLigne: "publications en ligne",
      publicationsTexte: "Les visuels affichés sur le site public.",
      publicationsNote: "Pour ajouter une publication, déposez le fichier dans public/flyers/ puis déclarez-le dans src/data/site.js.",
      statuts: {
        actif: "Actif", a_renouveler: "À renouveler", suspendu: "Suspendu",
        nouveau: "Nouveau", en_cours: "En cours", accepte: "Accepté", refuse: "Refusé",
        declare: "Déclaré", en_expertise: "En expertise", clos: "Clos",
      },
    },
    pied: { liens: "Navigation", coordonnees: "Coordonnées", droits: "Tous droits réservés." },
    flottant: { appeler: "Appeler l'agence", whatsapp: "Écrire sur WhatsApp", maps: "Voir sur Google Maps", haut: "Remonter en haut" },
  },

  ar: {
    dir: "rtl",
    nav: {
      accueil: "الرئيسية",
      assurances: "تأميناتنا",
      apropos: "من نحن",
      publications: "منشوراتنا",
      paiement: "الأداء",
      espace: "الإدارة",
      pourquoi: "لماذا نحن؟",
      faq: "أسئلة شائعة",
      contact: "اتصل بنا",
      devis: "اطلب عرض سعر",
      menu: "فتح القائمة",
      fermer: "إغلاق القائمة",
    },
    hero: {
      badge: "وكيل تأمين الوفاء",
      lieu: "المسيرة 2 – أبواب الضحى، مراكش",
      titre1: "تأمينك،",
      titre2: "التزامنا.",
      sous: "تأمينات أهل الخير ترافقكم بالمسيرة 2، أمام كارفور أبواب الضحى بمراكش، بحلول تأمينية تناسب احتياجاتكم.",
      devis: "اطلب عرض سعر",
      contact: "اتصل بنا",
      couverture: "ما نغطيه",
    },
    services: {
      titre: "حلولنا التأمينية",
      sous: "حلول تناسب الأفراد والمهنيين.",
      plus: "اعرف المزيد",
      liste: [
        ["تأمين السيارات", "احمِ سيارتك وقُد بكل اطمئنان."],
        ["تأمين السكن", "منزلك وممتلكاتك مغطاة يوميًا."],
        ["التأمين الصحي", "تغطية العلاج لك ولعائلتك."],
        ["تأمين الحوادث", "حماية في حالة حوادث الحياة اليومية."],
        ["التأمين المهني", "ضمانات تناسب نشاطك ومحلاتك."],
        ["تأمين السفر", "سافر مغطى، داخل المغرب وخارجه."],
      ],
    },
    agence: {
      titre: "وكالة قريبة منكم بالمسيرة 2",
      texte: "تقع تأمينات أهل الخير بالمسيرة 2، رقم 823 ب، أمام كارفور أبواب الضحى بمراكش، وترافقكم في إجراءاتكم التأمينية بخدمة قريبة ومواكبة شخصية.",
      bouton: "شاهد موقعنا",
      points: [["المسيرة 2، رقم 823 ب — مراكش", "أمام كارفور أبواب الضحى"], ["وكيل تأمين الوفاء", "شريكنا"], ["06 08 52 40 44", "للاتصال المباشر"]],
    },
    pourquoi: {
      titre: "لماذا تختار تأمينات أهل الخير؟",
      sous: "أربعة التزامات توجه عملنا يوميًا.",
      liste: [
        ["القرب", "وكالة محلية بالمسيرة 2، مراكش."],
        ["المواكبة", "مواكبة شخصية حسب احتياجاتكم."],
        ["الاستشارة", "نصائح تناسب وضعيتكم."],
        ["سرعة التجاوب", "فريق متاح للرد على طلباتكم."],
      ],
    },
    devis: {
      titre: "اطلب عرض السعر",
      sous: "صف حاجتك وسنعود إليك في أقرب وقت.",
      nom: "الاسم الكامل",
      tel: "الهاتف",
      email: "البريد الإلكتروني",
      type: "نوع التأمين",
      typeVide: "اختر نوع التأمين",
      message: "الرسالة",
      messagePlaceholder: "وضح حاجتك في بضعة أسطر",
      envoyer: "إرسال الطلب",
      envoi: "جاري الإرسال…",
      succesTitre: "تم إرسال الطلب",
      succesTexte: "شكرًا لك، تم استلام طلبك. سنتصل بك على الرقم المذكور.",
      autre: "إرسال طلب آخر",
      types: ["السيارات", "السكن", "الصحة", "الحوادث", "المهني", "السفر"],
      erreurs: {
        nom: "المرجو إدخال اسمك الكامل.",
        tel: "المرجو إدخال رقم هاتف صحيح.",
        email: "المرجو إدخال بريد إلكتروني صحيح.",
        type: "المرجو اختيار نوع التأمين.",
        message: "الرسالة قصيرة جدًا.",
      },
      note: "معلوماتك تُستعمل فقط لمعالجة طلبك.",
    },
    localisation: {
      titre: "تجدوننا بالمسيرة 2",
      sous: "المسيرة 2، رقم 823 ب، أمام كارفور أبواب الضحى — مراكش",
      maps: "عرض على خرائط جوجل",
      itineraire: "الاتجاهات",
      carte: "خريطة حي المسيرة 2، أمام كارفور أبواب الضحى بمراكش",
    },
    apropos: {
      titre: "عن تأمينات أهل الخير",
      p1: "تأمينات أهل الخير وكالة تأمين تقع بالمسيرة 2، رقم 823 ب، أمام كارفور أبواب الضحى بمراكش، وتعمل كوكيل لتأمين الوفاء.",
      p2: "هدفنا هو مواكبة زبنائنا بالقرب والاستشارة والاحترافية في احتياجاتهم التأمينية.",
    },
    faq: {
      titre: "أسئلة شائعة",
      sous: "أجوبة عن أكثر الطلبات تكرارًا.",
      liste: [
        ["كيف أطلب عرض سعر؟", "املأ استمارة طلب عرض السعر في هذه الصفحة، أو اتصل بنا مباشرة على 06 08 52 40 44. سنعود إليك باقتراح مناسب."],
        ["ما هي الوثائق اللازمة لتأمين السيارة؟", "البطاقة الرمادية للسيارة، البطاقة الوطنية ورخصة السياقة. إذا كانت السيارة مؤمنة سابقًا، أحضر أيضًا كشف المعلومات من شركة التأمين السابقة."],
        ["ما أنواع التأمينات التي تقدمونها؟", "نقدم تأمين السيارات، السكن، الصحة، الحوادث، التأمين المهني وتأمين السفر."],
        ["كيف أتصل بالوكالة؟", "عبر الهاتف أو واتساب على 06 08 52 40 44، أو بالمرور مباشرة إلى الوكالة."],
        ["أين توجد تأمينات أهل الخير؟", "توجد وكالتنا بالمسيرة 2، رقم 823 ب، أمام كارفور أبواب الضحى بمراكش."],
      ],
    },
    flyers: {
      titre: "منشوراتنا",
      sous: "حملات وعروض الوكالة الجارية.",
      agrandir: "تكبير",
      telecharger: "تحميل",
      fermer: "إغلاق",
      precedent: "المنشور السابق",
      suivant: "المنشور التالي",
    },
    conventions: {
      titre: "اتفاقياتنا",
      sous: "اتفاقيات موقعة مع مؤسسات مرجعية لفائدة منخرطيها.",
    },
    contact: {
      titre: "اتصل بنا",
      sous: "نجيب عن أسئلتكم ونوجهكم نحو التغطية المناسبة.",
      appeler: "اتصال",
      whatsapp: "واتساب",
      maps: "خرائط جوجل",
    },
    appel: {
      secours: "لم تبدأ المكالمة؟ اطلب هذا الرقم:",
      copier: "نسخ", copie: "تم النسخ", fermer: "إغلاق",
    },
    captcha: {
      label: "لست روبوتا",
      chargement: "جاري تحميل التحقق…",
      erreur: "المرجو تأكيد أنك لست روبوتا.",
    },
    paiement: {
      titre: "طرق الأداء",
      sous: "أدّ قسطك نقدا بالوكالة، دفعة واحدة أو بالتقسيط.",
      note: "لا يتم أي أداء عبر الإنترنت. جميع المدفوعات تتم مباشرة بالوكالة، مقابل وصل.",
      champ: "طريقة الأداء المرغوبة",
      champVide: "اختر طريقة الأداء",
    },
    assistant: {
      ouvrir: "المساعد الإلكتروني",
      titre: "مساعد أهل الخير",
      sous: "أجوبة فورية عن الأسئلة الشائعة",
      placeholder: "اطرح سؤالك…",
      envoyer: "إرسال",
      fermer: "إغلاق المساعد",
      accueil: "مرحبا. أجيب عن الأسئلة الشائعة حول تأميناتنا، عنوان الوكالة، الوثائق المطلوبة وطرق الأداء. للحصول على عرض سعر أو لملف شخصي، سيجيبكم مستشار مباشرة.",
      inconnu: "ليس لدي جواب عن هذا السؤال. مستشار الوكالة سيجيبكم أفضل مني.",
      suggestions: ["أين توجد الوكالة؟", "وثائق تأمين السيارة", "كيف أؤدي القسط؟", "التصريح بحادث"],
      appeler: "الاتصال بالوكالة",
      avertissement: "مساعد آلي. الأجوبة إرشادية ولا تعوض مستشاركم.",
    },
    connexion: {
      retour: "العودة إلى الموقع",
      reserve: "دخول محفوظ",
      titre: "الإدارة",
      sous: "هذا الفضاء محفوظ لفريق الوكالة. الزبناء يتصفحون الموقع بحرية ويتصلون بنا هاتفيا أو عبر واتساب.",
      pasDeCompte: "هل أنت زبون؟",
      retourSite: "العودة إلى الموقع",
      email: "البريد الإلكتروني",
      motDePasse: "كلمة المرور",
      afficher: "إظهار كلمة المرور",
      masquer: "إخفاء كلمة المرور",
      seConnecter: "دخول",
      envoi: "جاري الدخول…",
      demoTitre: "حساب تجريبي",
      erreurEmail: "المرجو إدخال بريدك الإلكتروني.",
      erreurMdp: "المرجو إدخال كلمة المرور.",
      erreurIdentifiants: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    },
    espace: {
      deconnexion: "خروج",
      administration: "الإدارة",
      demandes: "طلبات عروض الأسعار", sinistres: "الحوادث", tableauBord: "لوحة القيادة",
      clientsOnglet: "الزبناء", publications: "المنشورات",
      fiches: "بطاقات زبناء", telephone: "الهاتف", contrats: "العقود",
      primeAnnuelle: "القسط السنوي", appeler: "اتصال", telecharger: "تحميل",
      enAttente: "في انتظار المعالجة", dossiersOuverts: "ملفات مفتوحة", auTotal: "في المجموع",
      prendreEnCharge: "تكفل بالملف", accepter: "قبول", refuser: "رفض",
      mandater: "تعيين خبير", cloturer: "إغلاق",
      vueEnsemble: "نظرة عامة على نشاط الوكالة.",
      primesSignees: "الأقساط الموقعة", clients: "الزبناء", parProduit: "الطلبات حسب المنتوج",
      nom: "الاسم", statut: "الحالة", action: "إجراء",
      enLigne: "منشورات على الموقع",
      publicationsTexte: "الصور المعروضة في الموقع العمومي.",
      publicationsNote: "لإضافة منشور، ضع الملف في public/flyers/ ثم صرح به في src/data/site.js.",
      statuts: {
        actif: "نشط", a_renouveler: "للتجديد", suspendu: "موقوف",
        nouveau: "جديد", en_cours: "قيد المعالجة", accepte: "مقبول", refuse: "مرفوض",
        declare: "مصرح به", en_expertise: "قيد الخبرة", clos: "مغلق",
      },
    },
    pied: { liens: "التصفح", coordonnees: "معلومات الاتصال", droits: "جميع الحقوق محفوظة." },
    flottant: { appeler: "الاتصال بالوكالة", whatsapp: "الكتابة على واتساب", maps: "عرض على الخريطة", haut: "العودة للأعلى" },
  },
};
